export {
  PrismaClient,
  Prisma,
  Plan,
  UserRole,
  IvaCondition,
  StockMovementType,
  DocumentType,
  DocumentStatus,
  CcEntryType,
  PaymentMethod,
  CashSessionStatus,
  CashMovementType,
  PriceCoefficientScope,
  SalesOrderStatus,
} from '@prisma/client';
